<?php

function dna_menu() {
    $items = array();
    $items['dna-form'] = array(
        'title' => 'DNA Form',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('dna_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

    $items['dna_success'] = array(
        'title' => 'Half of the other DNA helix',
        'page callback' => 'dna_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    return $items;
}

//create an input form
function dna_form() {
    $form['dna'] = array(
        '#title' => 'DNA molecule',
        '#type' => 'textfield',
        '#description' => t('Enter one half of your DNA Helix, just 4 letters "A", "T", "C" & "G" only: '),
        '#element_validate' => array('element_validate_text'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Submit',
    );

    return $form;
}

//Validation the text input
function element_validate_text($element) {
    if(preg_match('/[^A T C G a t c g]/', $element['#value'])) {
        form_error($element, t('Only 4 letters "A", "T", "C" and "G" are accepted.'));
    }
};

function dna_complete($input){

    $dna_split = str_split(strtoupper($input));
    $half= array();
    $result=array();
    foreach ($dna_split as $element){
        if ($element == "A"){
            array_push($half, "T");
        };
        if ($element == "T"){
            array_push($half, "A");
        };
        if ($element == "C"){
            array_push( $half, "G");
        };
        if ($element == "G"){
            array_push( $half, "C");
        };
    }; //close foreach loop
    $result = implode(" ", $half);
    return $result;
};

//save input values in $_SESSION
function dna_form_submit($form, &$form_state) {
    $dna = $form_state['values']['dna'];
    $dna_completion = dna_complete($dna);
    $_SESSION['dna'] = $dna;
    $_SESSION['dna_completion'] = $dna_completion;
    $form_state['redirect'] = 'dna_success';
}

function dna_success(){
    $dna = $_SESSION['dna'];
    $dna_completion = $_SESSION['dna_completion'];

    return '<p>Your Helix is  '. $dna . '</p>' . '<p>The other half Helix is  '. $dna_completion. '</p>';
}; //close the function
